var serviceWorkerOption = {
  "assets": [
    "/match.html",
    "/matchDetail.html",
    "/nav.html",
    "/css/style.css",
    "/images/adidas.webp",
    "/images/cocacola.webp",
    "/images/ea-sports.webp",
    "/images/icon.png",
    "/images/logo.webp",
    "/images/nike.webp",
    "/images/underarmour.webp",
    "/images/xbox.webp",
    "/js/api.js",
    "/js/db.js",
    "/js/foot.js",
    "/js/idb.js",
    "/js/nav.js",
    "/js/register-push.js",
    "/js/register-sw.js",
    "/js/component/foot-bar.js",
    "/js/component/get-matches.js",
    "/js/component/get-scorers.js",
    "/js/component/nav-bar.js",
    "/js/component/nav-button.js",
    "/js/component/nav-detail.js",
    "/pages/about.html",
    "/pages/home.html",
    "/pages/saved_matches.html",
    "/pages/standings.html",
    "/pages/top_scorers.html",
    "/index.js",
    "/match.js",
    "/matchDetail.js",
    "/index.html",
    "/manifest.42c527516d9fb65b403f80f2c5829a06.json",
    "/icon_1024x1024.0823aab5af2c6959f6b6382e491bf345.png",
    "/images/icons/ios/icon_512x512.ae0d3ce9f649547ba237cc7535bf9e2c.png",
    "/images/icons/ios/icon_384x384.b3c94fb52ec5676599f25646785ba5f9.png",
    "/images/icons/ios/icon_256x256.e580adf2e92834a173bbe5f1fd376ea5.png",
    "/images/icons/ios/icon_192x192.8a01c4d595a2465d403a23533d1c63ba.png",
    "/images/icons/ios/icon_128x128.9a3c559aaf66bfcbd74b8437b9cbad2a.png",
    "/images/icons/ios/icon_96x96.2dc5aac5b7f433712828466e5fad7159.png"
  ]
};
        
        !function(e){var t={};function n(r){if(t[r])return t[r].exports;var i=t[r]={i:r,l:!1,exports:{}};return e[r].call(i.exports,i,i.exports,n),i.l=!0,i.exports}n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var i in e)n.d(r,i,function(t){return e[t]}.bind(null,i));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=0)}([function(e,t){var n="englishpremierleague-v1",r=serviceWorkerOption.assets;self.addEventListener("install",(function(e){e.waitUntil(caches.open(n).then((function(e){return e.addAll(r)})))})),self.addEventListener("fetch",(function(e){e.request.url.indexOf("https://api.football-data.org/v2/")>-1?e.respondWith(caches.open(n).then((function(t){return fetch(e.request).then((function(n){return t.put(e.request.url,n.clone()),n}))}))):e.respondWith(caches.match(e.request,{ignoreSearch:!0}).then((function(t){return t||fetch(e.request)})))})),self.addEventListener("activate",(function(e){e.waitUntil(caches.keys().then((function(e){return Promise.all(e.map((function(e){if(e!=n)return console.log("ServiceWorker: cache "+e+" dihapus"),caches.delete(e)})))})))})),self.addEventListener("push",(function(e){var t={body:e.data?e.data.text():"Push message no payload",icon:"./images/icon.png",badge:"./images/icon.png",requireInteraction:!0,vibrate:[100,50,100],data:{dateOfArrival:Date.now(),primaryKey:1}};e.waitUntil(self.registration.showNotification("English Premier League",t))}))}]);